package se.crisp.example.core;

import com.fasterxml.jackson.annotation.JsonProperty;

public class Greetings {
    @JsonProperty
    private String content;

    private Greetings() {
        // For Jackson deserialization
    }

    public Greetings(String content) {
        this.content = content;
    }

    public String getContent() {
        return content;
    }

    @Override
    // Generated by IntelliJ
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Greetings greetings = (Greetings) o;

        return !(content != null ? !content.equals(greetings.content) : greetings.content != null);

    }

    @Override
    // Generated by IntelliJ
    public int hashCode() {
        return content != null ? content.hashCode() : 0;
    }
}
