  version: '2'

  services:

    gitlab:
      build: ./gitlab
      container_name: gitlab
      image: cd-course/gitlab
      hostname: gitlab
      mem_limit: 2g
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://127.0.0.1:8050'
          gitlab_rails['gitlab_shell_ssh_port'] = 522
      ports:
        - "8050:8050"
        - "522:22"

    jenkins:
      build: ./jenkins
      image: cd-course/jenkins
      container_name: jenkins
      hostname: jenkins
      mem_limit: 2g
      ports:
        - "8080:8080"
        - "50000:50000"
      restart: "always"
      volumes:
        - ./jenkins-data:/var/jenkins_home

    nexus:
      build: ./nexus
      image: cd-course/nexus
      container_name: nexus
      hostname: nexus
      restart: "always"
      mem_limit: 4g
      environment:
        INSTALL4J_ADD_VM_PARAMS: "-Xmx3g"
      ports:
        - "8081:8081"
      volumes:
        - "./nexus-data:/nexus-data"

    test:
      build: ./test
      image: cd-course/test
      container_name: test
      hostname: test
      ports:
        - "18090:8090"
