  version: '2'

  services:

    gitlab:
      build: ./gitlab
      container_name: gitlab
      image: cd-course/gitlab
      hostname: gitlab
      mem_limit: 2gb
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://127.0.0.1:8050'
          gitlab_rails['gitlab_shell_ssh_port'] = 522
      ports:
        - "8050:8050"
        - "522:22"
      volumes:
        - ./gitlab-data/etc:/etc/gitlab
        - ./gitlab-data/logs:/var/log/gitlab
        - ./gitlab-data/data:/var/opt/gitlab

    jenkins:
      build: ./jenkins
      depends_on:
        - gitlab
        - nexus
      image: cd-course/jenkins
      container_name: jenkins
      hostname: jenkins
      mem_limit: 2gb
      ports:
        - "8080:8080"
        - "50000:50000"
      restart: "always"
      volumes:
        - ./jenkins-data:/var/jenkins_home

    nexus:
      build: ./nexus
      image: cd-course/nexus
      container_name: nexus
      hostname: nexus
      restart: "always"
      mem_limit: 4gb
      ports:
        - "8081:8081"
      volumes:
        - "./nexus-data:/nexus-data"
